Makefile: add dependency on zz_generated.deepcopy.go files
Otherwise, both the two below commands fail when deleting
`zz_generated.deepcopy.go` files.

```console
$ make build
go-bindata version 3.15.0
env GOBIN=/Users/marc/dev/bin time go generate ./pkg/nodebootstrap ./pkg/addons/default ./pkg/addons
        4.85 real         0.76 user         0.48 sys
CGO_ENABLED=0 time go build -ldflags "-X github.com/weaveworks/eksctl/pkg/version.gitCommit=0.2.0-801-g452dfb9e-dirty -X github.com/weaveworks/eksctl/pkg/version.builtAt=1573461216" ./cmd/eksctl
pkg/apis/eksctl.io/v1alpha5/register.go:42:3: cannot use &ClusterConfig literal (type *ClusterConfig) as type runtime.Object in argument to scheme.AddKnownTypes:
	*ClusterConfig does not implement runtime.Object (missing DeepCopyObject method)
pkg/apis/eksctl.io/v1alpha5/register.go:43:3: cannot use &ClusterConfigList literal (type *ClusterConfigList) as type runtime.Object in argument to scheme.AddKnownTypes:
	*ClusterConfigList does not implement runtime.Object (missing DeepCopyObject method)
        1.55 real         1.83 user         1.54 sys
make: *** [build] Error 2
```

```console
$ make generate-all
go-bindata version 3.15.0
env GOBIN=/Users/marc/dev/bin time go generate ./pkg/nodebootstrap ./pkg/addons/default ./pkg/addons
        4.87 real         0.74 user         0.47 sys
time go run ./cmd/schema/generate.go site/content/usage/20-schema.md
pkg/apis/eksctl.io/v1alpha5/register.go:42:3: cannot use &ClusterConfig literal (type *ClusterConfig) as type runtime.Object in argument to scheme.AddKnownTypes:
	*ClusterConfig does not implement runtime.Object (missing DeepCopyObject method)
pkg/apis/eksctl.io/v1alpha5/register.go:43:3: cannot use &ClusterConfigList literal (type *ClusterConfigList) as type runtime.Object in argument to scheme.AddKnownTypes:
	*ClusterConfigList does not implement runtime.Object (missing DeepCopyObject method)
        0.60 real         0.75 user         0.43 sys
make: *** [site/content/usage/20-schema.md] Error 2
```

Note that after this commit,

- running `make build` after deleting `zz_generated.deepcopy.go`
  regenerates them, but
- running `make build` again when these have been generated doesn't
  regenerate them again, which is hopefully what we want, given
  regenerating them takes ~3 seconds, which was thought as a "too long"
  in the past.